### ISSUE TITLE
Statoscope doesn't provide package versions with ModuleFederationPlugin

### ISSUE THREAD

**Issue by loshchini** [statoscope/statoscope#145]
**Describe the bug**
Statoscope report doesn't provide package versions when ModuleFederationPlugin is added to config and its `shared` option is specified.

**To Reproduce**
1. Clone the [repo](https://github.com/loshchini/statoscope-module-federation-example) 
2. Run `npm run build`
3. Open `./dist/build_info/statoscopeReport.html`
4. For example `antd` has no version detected 

<img width="802" alt="Screenshot 2021-12-06 at 14 20 55" src="https://user-images.githubusercontent.com/43792013/144837544-aa6ea3ed-cae7-42e6-aac5-636347ca8693.png">

5. Comment `shared` option or remove ModuleFederationPlugin from  [webpack.config.js](https://github.com/loshchini/statoscope-module-federation-example/blob/master/webpack.config.js#L88)
6. Repeat 2-3 steps
7. All package versions detected, `antd` for example
 
<img width="952" alt="Screenshot 2021-12-06 at 14 20 39" src="https://user-images.githubusercontent.com/43792013/144837534-a81e6c45-4aba-4f75-958f-0a2c9b7b49b2.png">

**Expected behavior**
Statoscope report correctly displays all package versions with ModuleFederationPlugin as well as without 

**Screenshots**
See above

**Versions**:
 - Node (for non-browser bug): 14.17.0
 - Webpack: 5.61.0
 - Statoscope: 5.19.0

**Additional context**
Thats important for CI tool we use, which grabbed info about package versions from Statoscope report

**Comment by smelukov** [comment]
@loshchini Thanks! I think I know how to fix it. Will be fixed soon

**Comment by smelukov** [comment]
Fixed in v5.19.1

**Comment by loshchini** [comment]
Thanks!

**Comment by loshchini** [comment]
Hi! 
In my example repo I bumped statoscope versions to 5.19.1 and for some packages versions still not detected.
For example `object-assign`

<img width="1657" alt="Screenshot 2022-01-11 at 15 01 36" src="https://user-images.githubusercontent.com/43792013/148939784-f2413d40-8673-4e0a-8d48-1260c2d5fe6a.png">

Sorry, should i create a new issue or we can discuss it and solve it right here?

**Comment by smelukov** [comment]
Hi. It's ok to discuss this problem here. I'll see how can I fix it
Thanks

**Comment by loshchini** [comment]
Thanks 🙏

**Comment by smelukov** [comment]
@loshchini Fixed in 5.19.3

**Comment by loshchini** [comment]
It wotks! Thank you :)
